version: '3.8'

services:
  core-api:
    build:
      context: ./core-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge